[package]
name = "ui_item"
version = "0.1.0"
edition = "2021"

[dependencies]
darling = "0.20"
glam = { version = "0.29", features = ["serde"] }
log = "0.4"

math_helpers = { path = "../math_helpers" }
