[package]
name = "imgui_wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.18"
bytemuck = { version = "1.14", features = [ "derive" ] }
imgui = "0.11"